---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    name: gatewayserver-app
