---
apiVersion: v1
kind: Service
metadata:
  name: tesseractserver-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 14121
      targetPort: 14121
  selector:
    name: tesseractserver-app
