grpc:
  port: 14122

minio:
  endpoint: localhost:9000
  accesskeyid: minioadmin
  secretaccesskey: minioadmin
  usessl: false

redis:
  addr: localhost:6379
  password:

bucket:
  name: pandora

storage:
  cache:
    prefix: storage
