grpc:
  port: 14122

minio:
  endpoint: 178.128.101.216:9000
  accesskeyid: admin
  secretaccesskey: some_random_password
  usessl: false

redis:
  addr: 159.65.13.169:6379
  password: some_random_password

rabbitmq:
  url: amqp://admin:some_random_password@159.65.140.204:5672/

gateway:
  cache:
    prefix: gateway
  urls:
    tesseract: localhost:14123
