name: Docker

on:
  push:
    branches: [master]

jobs:
  storage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/storage
          tags: latest
          dockerfile: deploy/docker/storage/Dockerfile
          cache_froms: cyndie7216/storage:latest

  gatewayserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/gatewayserver
          tags: latest
          dockerfile: deploy/docker/gatewayserver/Dockerfile
          cache_froms: cyndie7216/gatewayserver:latest

  aiserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/aiserver
          tags: latest
          dockerfile: deploy/docker/aiserver/Dockerfile
          cache_froms: cyndie7216/aiserver:latest

  aiprocessor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/aiprocessor
          tags: latest
          dockerfile: deploy/docker/aiprocessor/Dockerfile
          cache_froms: cyndie7216/aiprocessor:latest

  tesseract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/tesseract
          tags: latest
          dockerfile: deploy/docker/tesseract/Dockerfile
          cache_froms: cyndie7216/tesseract:latest

  tesseractserver:
    runs-on: ubuntu-latest
    needs: [aiserver]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/tesseractserver
          tags: latest
          dockerfile: deploy/docker/tesseractserver/Dockerfile
          cache_froms: cyndie7216/tesseractserver:latest

  tesseractprocessor:
    runs-on: ubuntu-latest
    needs: [aiprocessor, tesseract]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/tesseractprocessor
          tags: latest
          dockerfile: deploy/docker/tesseractprocessor/Dockerfile
          cache_froms: cyndie7216/tesseractprocessor:latest

  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/yolo
          tags: latest
          dockerfile: deploy/docker/yolo/Dockerfile
          cache_froms: cyndie7216/yolo:latest

  yoloserver:
    runs-on: ubuntu-latest
    needs: [aiserver]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/yoloserver
          tags: latest
          dockerfile: deploy/docker/yoloserver/Dockerfile
          cache_froms: cyndie7216/yoloserver:latest

  yoloprocessor:
    runs-on: ubuntu-latest
    needs: [aiprocessor, yolo]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/yoloprocessor
          tags: latest
          dockerfile: deploy/docker/yoloprocessor/Dockerfile
          cache_froms: cyndie7216/yoloprocessor:latest

  languagetool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/languagetool
          tags: latest
          dockerfile: deploy/docker/languagetool/Dockerfile
          cache_froms: cyndie7216/languagetool:latest

  languagetoolserver:
    runs-on: ubuntu-latest
    needs: [aiserver]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/languagetoolserver
          tags: latest
          dockerfile: deploy/docker/languagetoolserver/Dockerfile
          cache_froms: cyndie7216/languagetoolserver:latest

  languagetoolprocessor:
    runs-on: ubuntu-latest
    needs: [aiprocessor, languagetool]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/languagetoolprocessor
          tags: latest
          dockerfile: deploy/docker/languagetoolprocessor/Dockerfile
          cache_froms: cyndie7216/languagetoolprocessor:latest
