name: Docker

on:
  push:
    branches: [master]

jobs:
  storage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/storage
          tags: latest
          dockerfile: deploy/docker/storage/Dockerfile
          cache_froms: cyndie7216/storage

  gatewayserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/gatewayserver
          tags: latest
          dockerfile: deploy/docker/gatewayserver/Dockerfile
          cache_froms: cyndie7216/gatewayserver

  aiserver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/aiserver
          tags: latest
          dockerfile: deploy/docker/aiserver/Dockerfile
          cache_froms: cyndie7216/aiserver

  aiprocessor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/aiprocessor
          tags: latest
          dockerfile: deploy/docker/aiprocessor/Dockerfile
          cache_froms: cyndie7216/aiprocessor

  tesseractserver:
    runs-on: ubuntu-latest
    needs: [aiserver]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/tesseractserver
          tags: latest
          dockerfile: deploy/docker/tesseractserver/Dockerfile
          cache_froms: cyndie7216/tesseractserver

  tesseractprocessor:
    runs-on: ubuntu-latest
    needs: [aiprocessor]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/tesseractprocessor
          tags: latest
          dockerfile: deploy/docker/tesseractprocessor/Dockerfile
          cache_froms: cyndie7216/tesseractprocessor

  yoloserver:
    runs-on: ubuntu-latest
    needs: [aiserver]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/yoloserver
          tags: latest
          dockerfile: deploy/docker/yoloserver/Dockerfile
          cache_froms: cyndie7216/yoloserver

  yoloprocessor:
    runs-on: ubuntu-latest
    needs: [aiprocessor]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/yoloprocessor
          tags: latest
          dockerfile: deploy/docker/yoloprocessor/Dockerfile
          cache_froms: cyndie7216/yoloprocessor

  languagetoolserver:
    runs-on: ubuntu-latest
    needs: [aiserver]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/languagetoolserver
          tags: latest
          dockerfile: deploy/docker/languagetoolserver/Dockerfile
          cache_froms: cyndie7216/languagetoolserver

  languagetoolprocessor:
    runs-on: ubuntu-latest
    needs: [aiprocessor]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/languagetoolprocessor
          tags: latest
          dockerfile: deploy/docker/languagetoolprocessor/Dockerfile
          cache_froms: cyndie7216/languagetoolprocessor

  hcmtrafficserver:
    runs-on: ubuntu-latest
    needs: [aiserver]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/hcmtrafficserver
          tags: latest
          dockerfile: deploy/docker/hcmtrafficserver/Dockerfile
          cache_froms: cyndie7216/hcmtrafficserver

  hcmtrafficprocessor:
    runs-on: ubuntu-latest
    needs: [aiprocessor]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cyndie7216/hcmtrafficprocessor
          tags: latest
          dockerfile: deploy/docker/hcmtrafficprocessor/Dockerfile
          cache_froms: cyndie7216/hcmtrafficprocessor
